### ISSUE TITLE
Add "Toogle" Option

### ISSUE THREAD

**Issue by capstan1** [mlibre/hide-wingpanel#1]
Hi, really like your small script!

Would it be possible to add a "toggle-option" (or even make this default)?
The script could look if wingpanel is currently running and do kill or start depending on that. Like this we wouldn't need 2 shortcuts, but just one.

Also: ever thought of adding a small GUI and puttung this in AppCenter?

Best regards and thank you!

EDIT: just accomplished adding the toggle, if you are interested:
```
`#!/bin/bash

result=`ps aux | grep -i "wingpanel" | grep -v "grep" | wc -l`

if [ $result -ge 1 ]

   then

	killall cerbere &> /dev/null

	wait

	killall wingpanel &> /dev/null

      else

        wingpanel &> /dev/null &

fi`
```

**Comment by mlibre** [comment]
ty. I rly have no time for developing hide-wingpanel right now. but the license is CC0. you can put it in appCenter by your name as creator :).
