### ISSUE TITLE
Bug in elementary 5.1.3

### ISSUE THREAD

**Issue by workstation-i** [mlibre/hide-wingpanel#6]
- System: elementary 5.1.3
- issue
After reboot, need running `hide_top_panel` twice in terminal to hide wingpanel successfully.

![Screenshot from 2020-04-19 02-09-20](https://user-images.githubusercontent.com/52375886/79680898-d25b1d00-81e2-11ea-98e4-72a3e05d0c52.png)

**Comment by mlibre** [comment]
hey. I have added more kills :) that is all!
I hope it works
I don't know how should I disable that watcher.
https://github.com/mlibre/hide-wingpanel/issues/5

**Comment by in-character** [comment]
I have ubuntu installed in my laptop now, so I can't test it, maybe next time

**Comment by i-workstation** [comment]
oh, the problem still exists.

**Comment by mlibre** [comment]
so i probably need to install elementary in VM and fix it

**Comment by workstation-i** [comment]
Good job!

**Comment by workstation-i** [comment]
After executing `show_hide_top_panel.bash`, need to add `hide_top_panel` to startup.

**Comment by mlibre** [comment]
yeh. it is also good idea. possible to make a startup script also
